# AltFinder configuration

storage:
  sqlite:
    enabled: true # This option currently does nothing because there are no other storage options atm
    file: altfinder.db

notifications:
  # Enable notifications for potential alts to altfinder.notify
  enabled: true
  message: "&c[Alt Alert] &f%player_name% &6has a potential alt detected! "
tracking:
  # Store IP history for players
  log-ip-addresses: true

  # Store username history for players
  log-username-changes: true

  # How many days a username change is considered "recent"
  recent-name-change-days: 30

limits:
  concurrent-alts:
    # Maximum number of accounts allowed online at the same time
    # -1 = unlimited, 0 = no alts
    max: -1
    kick-message: '&cPlease log out of another account first.'

commands:
  seen:
    show-ip-by-default: false
    require-permission-for-ip: true
  search:
    results-per-page: 10